Upgrade to Apache Maven 3.10.0
Temporarily skip the SureFire Plugin tests to avoid the following errors:

[ERROR] Failures:
[ERROR]   RepositorySystemSupplierTest.smoke:60 expected: <true> but was: <false>
[ERROR] Errors:
[ERROR]   RepositorySystemSupplierTest.smokeV2Feature:82 » DependencyCollection Failed to
          read artifact descriptor for org.apache.maven:maven-resolver-provider:jar:3.6.1
[ERROR] Tests run: 34, Failures: 1, Errors: 1, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.6.0:test
        (default-test) on project maven-resolver-provider: There are test failures.

Caused by: java.net.UnknownHostException: repo.maven.apache.org